name: Build static binary

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: "ubuntu-22.04"

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v3"

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "latest"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v2"
      with:
        dependency-versions: "highest"

    - name: Install Box
      run: |
        wget \
          "https://github.com/box-project/box/releases/latest/download/box.phar" \
          --quiet \
          -O ./box
        chmod +x ./box
        sudo mv ./box /usr/local/bin  

    - name: Run Box
      run: box compile

    - name: Prepend the PHAR with micro.sfx
      run: cat micro-cli.sfx static.phar > static && chmod +x static

    - name: Store binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: static-binary
        path: static
